import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row h-screen w-screen bg-red-500">
          <div className="w-64 bg-green-500 h-full"></div>
          {children}
        </div>
      </body>
    </html>
  );
}
