import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import Navbar from '../components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-light-pink flex justify-center align-center">
          <div className='w-[95%] h-[100%] flex flex-row'>
            <Navbar />
            <div className='w-[80%] h-[100%] bg-white'>
              <div className='w-[100%] h-[27%] flex justify-center items-center'>
                <div className='w-[95%] h-[80%] bg-[#999999] rounded-l'></div>
              </div>
              <div className='w-[100%] h-[73%]'>
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
