import '@mantine/core/styles.css';
import '@mantine/dropzone/styles.css';

import Navbar from '@/components/Navbar/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div className="w-screen h-screen flex justify-center align-center">
      <div className="w-full h-[100%] flex flex-row">
        <Navbar />
        <div className="w-[80%] h-[100%] bg-white overflow-y-auto">
          <div className="w-[100%] h-[27%] flex justify-center items-center">
            <div className="w-[95%] h-[80%] bg-[#999999] rounded-l"></div>
          </div>
          <div className="w-[100%] h-[73%]">{children}</div>
        </div>
      </div>
    </div>
  );
}
